### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by dandv** [halhen/viz-pub#2]
This got picked up in the internal news at my employer.

Would be interesting to know the source, at least.

**Comment by halhen** [comment]
Hi! 

I added a README to the project, but realize that you maybe hoped to get more info on one of the projects? I do add the source of each viz in the footer, but maybe you wanted to ask something else?

I might be slow to respond on github, if you'd like to ask anything else, do send me a PM on Twitter @hnrklndbrg or email me at henrik@k2h.se.
